//Clase donde esta el login de aplicacion 
package Login;

import Conexion.AppSesion;
import Conexion.ConexionBBDD;
import Inicio.PantallaInicio;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.Area;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipalLogin = new javax.swing.JPanel();
        jLabelFotoLogin = new javax.swing.JLabel();
        jPanelArrastrarLogin = new javax.swing.JPanel();
        jLabelTextoInicialSesionLogin = new javax.swing.JLabel();
        jLabelTextoUsuarioLogin = new javax.swing.JLabel();
        jTextFieldIngresaUsuarioLogin = new javax.swing.JTextField();
        jSeparatorLogin = new javax.swing.JSeparator();
        jLabelTextoContraseñaLogin = new javax.swing.JLabel();
        jSeparatorLogin2 = new javax.swing.JSeparator();
        jPasswordIngresaContraseñaLogin = new javax.swing.JPasswordField();
        jPanelIniciarSesionLogin = new PanelRound();
        jLabelTextoIniciarLogin = new javax.swing.JLabel();
        jPanelSalirLogin = new javax.swing.JPanel();
        jLabelSalirLogin = new javax.swing.JLabel();
        jPanelMinimizarLogin = new javax.swing.JPanel();
        jLabelMinimizarLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanelPrincipalLogin.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipalLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFotoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenLoginN.png"))); // NOI18N
        jPanelPrincipalLogin.add(jLabelFotoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 440, 500));

        jPanelArrastrarLogin.setBackground(new java.awt.Color(255, 255, 255));
        jPanelArrastrarLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelArrastrarLoginMouseDragged(evt);
            }
        });
        jPanelArrastrarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelArrastrarLoginMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelArrastrarLoginLayout = new javax.swing.GroupLayout(jPanelArrastrarLogin);
        jPanelArrastrarLogin.setLayout(jPanelArrastrarLoginLayout);
        jPanelArrastrarLoginLayout.setHorizontalGroup(
            jPanelArrastrarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanelArrastrarLoginLayout.setVerticalGroup(
            jPanelArrastrarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelPrincipalLogin.add(jPanelArrastrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 740, 30));

        jLabelTextoInicialSesionLogin.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabelTextoInicialSesionLogin.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTextoInicialSesionLogin.setText("INCIAR SESIÓN");
        jPanelPrincipalLogin.add(jLabelTextoInicialSesionLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabelTextoUsuarioLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelTextoUsuarioLogin.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTextoUsuarioLogin.setText("USUARIO");
        jPanelPrincipalLogin.add(jLabelTextoUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jTextFieldIngresaUsuarioLogin.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIngresaUsuarioLogin.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jTextFieldIngresaUsuarioLogin.setText("Ingrese su nombre de usuario");
        jTextFieldIngresaUsuarioLogin.setBorder(null);
        jTextFieldIngresaUsuarioLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldIngresaUsuarioLoginMousePressed(evt);
            }
        });
        jPanelPrincipalLogin.add(jTextFieldIngresaUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, 30));
        jPanelPrincipalLogin.add(jSeparatorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, -1));

        jLabelTextoContraseñaLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelTextoContraseñaLogin.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTextoContraseñaLogin.setText("CONTRASEÑA");
        jPanelPrincipalLogin.add(jLabelTextoContraseñaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        jPanelPrincipalLogin.add(jSeparatorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 320, -1));

        jPasswordIngresaContraseñaLogin.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordIngresaContraseñaLogin.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jPasswordIngresaContraseñaLogin.setText("********");
        jPasswordIngresaContraseñaLogin.setBorder(null);
        jPasswordIngresaContraseñaLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordIngresaContraseñaLoginMousePressed(evt);
            }
        });
        jPanelPrincipalLogin.add(jPasswordIngresaContraseñaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        jPanelIniciarSesionLogin.setBackground(new java.awt.Color(15, 150, 189));
        jPanelIniciarSesionLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextoIniciarLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelTextoIniciarLogin.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTextoIniciarLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoIniciarLogin.setText("INICIAR");
        jLabelTextoIniciarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTextoIniciarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTextoIniciarLoginMouseClicked(evt);
            }
        });
        jPanelIniciarSesionLogin.add(jLabelTextoIniciarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        jPanelPrincipalLogin.add(jPanelIniciarSesionLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 120, 50));

        jPanelSalirLogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSalirLogin.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSalirLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelSalirLogin.setForeground(new java.awt.Color(51, 51, 51));
        jLabelSalirLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalirLogin.setText("X");
        jLabelSalirLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSalirLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSalirLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSalirLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalirLoginLayout = new javax.swing.GroupLayout(jPanelSalirLogin);
        jPanelSalirLogin.setLayout(jPanelSalirLoginLayout);
        jPanelSalirLoginLayout.setHorizontalGroup(
            jPanelSalirLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSalirLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanelSalirLoginLayout.setVerticalGroup(
            jPanelSalirLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSalirLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanelPrincipalLogin.add(jPanelSalirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanelMinimizarLogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabelMinimizarLogin.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMinimizarLogin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelMinimizarLogin.setForeground(new java.awt.Color(51, 51, 51));
        jLabelMinimizarLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMinimizarLogin.setText("-");
        jLabelMinimizarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimizarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizarLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizarLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizarLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMinimizarLoginLayout = new javax.swing.GroupLayout(jPanelMinimizarLogin);
        jPanelMinimizarLogin.setLayout(jPanelMinimizarLoginLayout);
        jPanelMinimizarLoginLayout.setHorizontalGroup(
            jPanelMinimizarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizarLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMinimizarLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );
        jPanelMinimizarLoginLayout.setVerticalGroup(
            jPanelMinimizarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMinimizarLoginLayout.createSequentialGroup()
                .addComponent(jLabelMinimizarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPrincipalLogin.add(jPanelMinimizarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Guarda las coordenadas del ratón al hacer clic para poder mover la ventana.
    private void jPanelArrastrarLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelArrastrarLoginMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();       
    }//GEN-LAST:event_jPanelArrastrarLoginMousePressed

    // Calcula la nueva posición de la ventana al arrastrarla con el ratón.
    private void jPanelArrastrarLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelArrastrarLoginMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse ,y - yMouse);
    }//GEN-LAST:event_jPanelArrastrarLoginMouseDragged

    // Cierra completamente la aplicación cuando se hace clic en la "X".
    private void jLabelSalirLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirLoginMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelSalirLoginMouseClicked

    // Limpia el campo de texto del usuario si tiene el texto por defecto, y restaura el texto por defecto en la contraseña si está vacía.
    private void jTextFieldIngresaUsuarioLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngresaUsuarioLoginMousePressed
        if(jTextFieldIngresaUsuarioLogin.getText().equals("Ingrese su nombre de usuario")){
            jTextFieldIngresaUsuarioLogin.setText("");    
        }
        if(String.valueOf(jPasswordIngresaContraseñaLogin.getPassword()).isEmpty()){
            jPasswordIngresaContraseñaLogin.setText("********");    
        }        
    }//GEN-LAST:event_jTextFieldIngresaUsuarioLoginMousePressed

    // Limpia el campo de contraseña si tiene el texto por defecto y muestra el texto por defecto del usuario si está vacío.
    private void jPasswordIngresaContraseñaLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordIngresaContraseñaLoginMousePressed
        
        if(String.valueOf(jPasswordIngresaContraseñaLogin.getPassword()).equals("********")){
            jPasswordIngresaContraseñaLogin.setText("");    
        }
        
        if(jTextFieldIngresaUsuarioLogin.getText().isEmpty()){
            jTextFieldIngresaUsuarioLogin.setText("Ingrese su nombre de usuario");    
        }       
    }//GEN-LAST:event_jPasswordIngresaContraseñaLoginMousePressed

    // Intenta iniciar sesión con los datos ingresados, conecta a la base de datos y abre la pantalla principal si es exitoso.
    private void jLabelTextoIniciarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoIniciarLoginMouseClicked
        String usuario = jTextFieldIngresaUsuarioLogin.getText();
        String contraseña = new String(jPasswordIngresaContraseñaLogin.getPassword());
        int intentos = 0;
        AppSesion.setCredenciales(usuario, contraseña);
        ConexionBBDD conexion = new ConexionBBDD();
        if(conexion.estaConectado()){
            JOptionPane.showMessageDialog(null, "Conexión exitosa");
            dispose();
            new PantallaInicio().setVisible(true);
        }else{
            intentos++;
            if(intentos >= 5){
                JOptionPane.showMessageDialog(null, "Demasiados intentos. Cerrando...");
                System.exit(0);
            }else{
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos. Intento " + intentos + "/5");
                jPasswordIngresaContraseñaLogin.setText("********");
            }
        }
    }//GEN-LAST:event_jLabelTextoIniciarLoginMouseClicked

    // Cambia el color de fondo del botón de cerrar a rojo al pasar el ratón sobre él.
    private void jLabelSalirLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirLoginMouseEntered
        jPanelSalirLogin.setBackground(Color.RED);
    }//GEN-LAST:event_jLabelSalirLoginMouseEntered

    // Restaura el color de fondo del botón de cerrar al color blanco cuando el ratón sale.
    private void jLabelSalirLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirLoginMouseExited
        jPanelSalirLogin.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jLabelSalirLoginMouseExited

    // Evento para minimizar al hacer clic en el JLabel minimizar
    private void jLabelMinimizarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarLoginMouseClicked
        this.setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizarLoginMouseClicked

    // Cambiar el fondo del panel "minimizar" a gris cuando se pasa el ratón
    private void jLabelMinimizarLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarLoginMouseEntered
        jPanelMinimizarLogin.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_jLabelMinimizarLoginMouseEntered

    // Restaurar el fondo del panel "minimizar" al color original cuando se quita el ratón
    private void jLabelMinimizarLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarLoginMouseExited
        jPanelMinimizarLogin.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelMinimizarLoginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFotoLogin;
    private javax.swing.JLabel jLabelMinimizarLogin;
    private javax.swing.JLabel jLabelSalirLogin;
    private javax.swing.JLabel jLabelTextoContraseñaLogin;
    private javax.swing.JLabel jLabelTextoInicialSesionLogin;
    private javax.swing.JLabel jLabelTextoIniciarLogin;
    private javax.swing.JLabel jLabelTextoUsuarioLogin;
    private javax.swing.JPanel jPanelArrastrarLogin;
    private javax.swing.JPanel jPanelIniciarSesionLogin;
    private javax.swing.JPanel jPanelMinimizarLogin;
    private javax.swing.JPanel jPanelPrincipalLogin;
    private javax.swing.JPanel jPanelSalirLogin;
    private javax.swing.JPasswordField jPasswordIngresaContraseñaLogin;
    private javax.swing.JSeparator jSeparatorLogin;
    private javax.swing.JSeparator jSeparatorLogin2;
    private javax.swing.JTextField jTextFieldIngresaUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}

// Clase auxiliar para redondear los paneles
class PanelRound extends JPanel {

    private int roundTopLeft = 50;
    private int roundTopRight = 50;
    private int roundBottomLeft = 50;
    private int roundBottomRight = 50;

    public PanelRound() {
        setOpaque(false);
    }

    public int getRoundTopLeft() {
        return roundTopLeft;
    }

    public void setRoundTopLeft(int roundTopLeft) {
        this.roundTopLeft = roundTopLeft;
        repaint();
    }

    public int getRoundTopRight() {
        return roundTopRight;
    }

    public void setRoundTopRight(int roundTopRight) {
        this.roundTopRight = roundTopRight;
        repaint();
    }

    public int getRoundBottomLeft() {
        return roundBottomLeft;
    }

    public void setRoundBottomLeft(int roundBottomLeft) {
        this.roundBottomLeft = roundBottomLeft;
        repaint();
    }

    public int getRoundBottomRight() {
        return roundBottomRight;
    }

    public void setRoundBottomRight(int roundBottomRight) {
        this.roundBottomRight = roundBottomRight;
        repaint();
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        Area area = new Area(createRoundTopLeft());
        if (roundTopRight > 0) {
            area.intersect(new Area(createRoundTopRight()));
        }
        if (roundBottomLeft > 0) {
            area.intersect(new Area(createRoundBottomLeft()));
        }
        if (roundBottomRight > 0) {
            area.intersect(new Area(createRoundBottomRight()));
        }
        g2.fill(area);
        g2.dispose();
        super.paintComponent(grphcs);
    }

    private Shape createRoundTopLeft() {
        int width = getWidth();
        int height = getHeight();
        int roundX = Math.min(width, roundTopLeft);
        int roundY = Math.min(height, roundTopLeft);
        Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, roundX, roundY));
        area.add(new Area(new Rectangle2D.Double(roundX / 2, 0, width - roundX / 2, height)));
        area.add(new Area(new Rectangle2D.Double(0, roundY / 2, width, height - roundY / 2)));
        return area;
    }

    private Shape createRoundTopRight() {
        int width = getWidth();
        int height = getHeight();
        int roundX = Math.min(width, roundTopRight);
        int roundY = Math.min(height, roundTopRight);
        Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, roundX, roundY));
        area.add(new Area(new Rectangle2D.Double(0, 0, width - roundX / 2, height)));
        area.add(new Area(new Rectangle2D.Double(0, roundY / 2, width, height - roundY / 2)));
        return area;
    }

    private Shape createRoundBottomLeft() {
        int width = getWidth();
        int height = getHeight();
        int roundX = Math.min(width, roundBottomLeft);
        int roundY = Math.min(height, roundBottomLeft);
        Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, roundX, roundY));
        area.add(new Area(new Rectangle2D.Double(roundX / 2, 0, width - roundX / 2, height)));
        area.add(new Area(new Rectangle2D.Double(0, 0, width, height - roundY / 2)));
        return area;
    }

    private Shape createRoundBottomRight() {
        int width = getWidth();
        int height = getHeight();
        int roundX = Math.min(width, roundBottomRight);
        int roundY = Math.min(height, roundBottomRight);
        Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, roundX, roundY));
        area.add(new Area(new Rectangle2D.Double(0, 0, width - roundX / 2, height)));
        area.add(new Area(new Rectangle2D.Double(0, 0, width, height - roundY / 2)));
        return area;
    }
}

