// Clase que representa el panel para añadir nuevas empresas a la base de datos.
package Inicio;

import Conexion.ConexionBBDD;
import com.formdev.flatlaf.ui.FlatComboBoxUI;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class PanelAñadir extends javax.swing.JPanel {
    private final PantallaInicio contro;
    
    public PanelAñadir(PantallaInicio contro) {
        this.contro = contro;
        initComponents();
        contro.cargarComunidadesEn(jComboBoxComunidadAñadir);
        aplicarFlatLafSoloCombosEnContenedir(this);
        aplicarTextoBlnacoEnCampo();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTextoTituloAñadir = new javax.swing.JLabel();
        jLabelTextoTelefonoAñadir = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelTextoIdEmpresaAñadir = new javax.swing.JLabel();
        jTextFieldNombreEmpresaAñadir = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelTextoNombreEmpresaAñadir = new javax.swing.JLabel();
        jLabelTextoActividadAñadir = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelTextoSectorAñadir = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelTextoEmailAñadir = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabelTextoFaxAñadir = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabelTextoDireccionAñadir = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabelTextoCodigoPostalAñadir = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabelTextoComunidadAñadir = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabelTextoProvinciaAñadir = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabelTextoPoblacionAñadir = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jLabelTextoEmailTestAñadir = new javax.swing.JLabel();
        jLabelTextoWebAñadir = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jTextFieldActividadAñadir = new javax.swing.JTextField();
        jTextFieldSectorAñadir = new javax.swing.JTextField();
        jTextFieldEmailAñadir = new javax.swing.JTextField();
        jTextFieldFaxAñadir = new javax.swing.JTextField();
        jTextFieldTelefonoAñadir = new javax.swing.JTextField();
        jTextFieldDireccionAñadir = new javax.swing.JTextField();
        jTextFieldCodigoPostalAñadir = new javax.swing.JTextField();
        jTextFieldPoblacionAñadir = new javax.swing.JTextField();
        jTextFieldEmailTestAñadir = new javax.swing.JTextField();
        jTextFieldWebAñadir = new javax.swing.JTextField();
        jTextFieldIdEmpresaAñadir = new javax.swing.JTextField();
        jComboBoxProvinciaAñadir = new javax.swing.JComboBox<>();
        jComboBoxComunidadAñadir = new javax.swing.JComboBox<>();
        jPanelAñadir = new PanelRound();
        jLabelTextoAñadir = new javax.swing.JLabel();
        jPanelIdAleatorioAñadir = new PanelRound();
        jLabelTextoIdAleatorioAñadir = new javax.swing.JLabel();
        jLabelImagenAñadir = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextoTituloAñadir.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextoTituloAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelTextoTituloAñadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoTituloAñadir.setText("AÑADA UNA EMPRESA");
        add(jLabelTextoTituloAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabelTextoTelefonoAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoTelefonoAñadir.setText("TELEFONO");
        add(jLabelTextoTelefonoAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 260, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 290, 10));

        jLabelTextoIdEmpresaAñadir.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextoIdEmpresaAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoIdEmpresaAñadir.setText("ID EMPRESA");
        add(jLabelTextoIdEmpresaAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jTextFieldNombreEmpresaAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldNombreEmpresaAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldNombreEmpresaAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldNombreEmpresaAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldNombreEmpresaAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 250, 25));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 260, 10));

        jLabelTextoNombreEmpresaAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoNombreEmpresaAñadir.setText("NOMBRE EMPRESA");
        add(jLabelTextoNombreEmpresaAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabelTextoActividadAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoActividadAñadir.setText("ACTIVIDAD");
        add(jLabelTextoActividadAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 260, 10));

        jLabelTextoSectorAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoSectorAñadir.setText("SECTOR");
        add(jLabelTextoSectorAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 260, 10));

        jLabelTextoEmailAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoEmailAñadir.setText("EMAIL");
        add(jLabelTextoEmailAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 260, 10));

        jLabelTextoFaxAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoFaxAñadir.setText("FAX");
        add(jLabelTextoFaxAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 260, -1));

        jLabelTextoDireccionAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoDireccionAñadir.setText("DIRECCIÓN");
        add(jLabelTextoDireccionAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 260, 10));

        jLabelTextoCodigoPostalAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoCodigoPostalAñadir.setText("CODIGO POSTAL");
        add(jLabelTextoCodigoPostalAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 260, 10));

        jLabelTextoComunidadAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoComunidadAñadir.setText("COMUNIDAD");
        add(jLabelTextoComunidadAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));
        add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 260, 10));

        jLabelTextoProvinciaAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoProvinciaAñadir.setText("PROVINCIA");
        add(jLabelTextoProvinciaAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));
        add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 260, 10));

        jLabelTextoPoblacionAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoPoblacionAñadir.setText("POBLACIÓN");
        add(jLabelTextoPoblacionAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));
        add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 260, 10));

        jLabelTextoEmailTestAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoEmailTestAñadir.setText("EMAIL_TEST");
        add(jLabelTextoEmailTestAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        jLabelTextoWebAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoWebAñadir.setText("WEB");
        add(jLabelTextoWebAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, -1, -1));
        add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 260, 10));

        jTextFieldActividadAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldActividadAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldActividadAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldActividadAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldActividadAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 250, 25));

        jTextFieldSectorAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldSectorAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldSectorAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldSectorAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldSectorAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 250, 25));

        jTextFieldEmailAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldEmailAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldEmailAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldEmailAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldEmailAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 250, 25));

        jTextFieldFaxAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldFaxAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldFaxAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldFaxAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldFaxAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 250, 25));

        jTextFieldTelefonoAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldTelefonoAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldTelefonoAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldTelefonoAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldTelefonoAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 250, 25));

        jTextFieldDireccionAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldDireccionAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldDireccionAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldDireccionAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldDireccionAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 250, 25));

        jTextFieldCodigoPostalAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldCodigoPostalAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldCodigoPostalAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldCodigoPostalAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldCodigoPostalAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 250, 25));

        jTextFieldPoblacionAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldPoblacionAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldPoblacionAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        jTextFieldPoblacionAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldPoblacionAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 250, 25));

        jTextFieldEmailTestAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldEmailTestAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldEmailTestAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldEmailTestAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldEmailTestAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 250, 25));

        jTextFieldWebAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldWebAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldWebAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldWebAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldWebAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 250, 25));

        jTextFieldIdEmpresaAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldIdEmpresaAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldIdEmpresaAñadir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldIdEmpresaAñadir.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldIdEmpresaAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, 25));

        jComboBoxProvinciaAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jComboBoxProvinciaAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        add(jComboBoxProvinciaAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 250, 25));

        jComboBoxComunidadAñadir.setBackground(new java.awt.Color(90, 90, 90));
        jComboBoxComunidadAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jComboBoxComunidadAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxComunidadAñadirActionPerformed(evt);
            }
        });
        add(jComboBoxComunidadAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 250, 25));

        jPanelAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelTextoAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoAñadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoAñadir.setText("AÑADIR");
        jLabelTextoAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTextoAñadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTextoAñadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTextoAñadirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelAñadirLayout = new javax.swing.GroupLayout(jPanelAñadir);
        jPanelAñadir.setLayout(jPanelAñadirLayout);
        jPanelAñadirLayout.setHorizontalGroup(
            jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTextoAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanelAñadirLayout.setVerticalGroup(
            jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTextoAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanelAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 120, 40));

        jPanelIdAleatorioAñadir.setBackground(new java.awt.Color(51, 51, 51));
        jPanelIdAleatorioAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelTextoIdAleatorioAñadir.setBackground(new java.awt.Color(51, 51, 51));
        jLabelTextoIdAleatorioAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        jLabelTextoIdAleatorioAñadir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoIdAleatorioAñadir.setText("ID ALEATORIO");
        jLabelTextoIdAleatorioAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTextoIdAleatorioAñadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTextoIdAleatorioAñadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTextoIdAleatorioAñadirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelIdAleatorioAñadirLayout = new javax.swing.GroupLayout(jPanelIdAleatorioAñadir);
        jPanelIdAleatorioAñadir.setLayout(jPanelIdAleatorioAñadirLayout);
        jPanelIdAleatorioAñadirLayout.setHorizontalGroup(
            jPanelIdAleatorioAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanelIdAleatorioAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelIdAleatorioAñadirLayout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(jLabelTextoIdAleatorioAñadir)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );
        jPanelIdAleatorioAñadirLayout.setVerticalGroup(
            jPanelIdAleatorioAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(jPanelIdAleatorioAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelIdAleatorioAñadirLayout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(jLabelTextoIdAleatorioAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        add(jPanelIdAleatorioAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 110, 34));

        jLabelImagenAñadir.setBackground(new java.awt.Color(255, 255, 255));
        jLabelImagenAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenFondo.png"))); // NOI18N
        jLabelImagenAñadir.setText("jLabel9");
        add(jLabelImagenAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 660));
    }// </editor-fold>//GEN-END:initComponents

    // Genera un ID aleatorio al hacer clic en el texto correspondiente.
    private void jLabelTextoIdAleatorioAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoIdAleatorioAñadirMouseClicked
        String idGenerado = generarIdUnico();
        jTextFieldIdEmpresaAñadir.setText(idGenerado);
    }//GEN-LAST:event_jLabelTextoIdAleatorioAñadirMouseClicked
    
    // Cambia el color del botón "Id aleatorio" al pasar el ratón por encima.
    private void jLabelTextoIdAleatorioAñadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoIdAleatorioAñadirMouseEntered
        jPanelIdAleatorioAñadir.setBackground(new Color(51, 51, 51));
        jLabelTextoIdAleatorioAñadir.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelTextoIdAleatorioAñadirMouseEntered

    // Restaura el color original del botón "Id aleatorio" al quitar el ratón.
    private void jLabelTextoIdAleatorioAñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoIdAleatorioAñadirMouseExited
        jPanelIdAleatorioAñadir.setBackground(Color.WHITE);
        jLabelTextoIdAleatorioAñadir.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabelTextoIdAleatorioAñadirMouseExited

    // Inserta una nueva empresa en la base de datos con los datos del formulario.
    private void jLabelTextoAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoAñadirMouseClicked
        String id = jTextFieldIdEmpresaAñadir.getText();
        String empresa = jTextFieldNombreEmpresaAñadir.getText();
        String actividad = jTextFieldActividadAñadir.getText();
        String sector = jTextFieldSectorAñadir.getText();
        String direccion = jTextFieldDireccionAñadir.getText();
        String cp = jTextFieldCodigoPostalAñadir.getText();
        String poblacion = jTextFieldPoblacionAñadir.getText();
        String provincia =  (String) jComboBoxProvinciaAñadir.getSelectedItem(); 
        String comunidad = (String) jComboBoxComunidadAñadir.getSelectedItem(); 
        String telefono = jTextFieldTelefonoAñadir.getText();
        String fax = jTextFieldFaxAñadir.getText();
        String email = jTextFieldEmailAñadir.getText();
        String emailTest = jTextFieldEmailTestAñadir.getText();
        String web = jTextFieldWebAñadir.getText();
        
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo ID es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        ConexionBBDD conexion = new ConexionBBDD();
        boolean insertado = conexion.insertarEmpresa(
                id, empresa, actividad, sector, direccion, cp,
                poblacion, provincia, comunidad, telefono, fax,
                email, emailTest, web, null
        );
        conexion.cerrarConexion();
        
        if(insertado){
            JOptionPane.showMessageDialog(this,"Empresa añadida correctamente");
            
            jTextFieldIdEmpresaAñadir.setText("");
            jTextFieldNombreEmpresaAñadir.setText("");
            jTextFieldActividadAñadir.setText("");
            jTextFieldSectorAñadir.setText("");
            jTextFieldDireccionAñadir.setText("");
            jTextFieldCodigoPostalAñadir.setText("");
            jTextFieldPoblacionAñadir.setText("");
            jComboBoxProvinciaAñadir.setSelectedIndex(-1);
            jComboBoxComunidadAñadir.setSelectedIndex(-1);
            jTextFieldTelefonoAñadir.setText("");
            jTextFieldFaxAñadir.setText("");
            jTextFieldEmailAñadir.setText("");
            jTextFieldEmailTestAñadir.setText("");
            jTextFieldWebAñadir.setText("");
        }else{
            JOptionPane.showMessageDialog(this,"Error al añadir la empresa", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelTextoAñadirMouseClicked

    // Cambia el color del botón "Añadir" al pasar el ratón por encima.
    private void jLabelTextoAñadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoAñadirMouseEntered
        jPanelAñadir.setBackground(new Color(51, 51, 51));
        jLabelTextoAñadir.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelTextoAñadirMouseEntered
    
    // Restaura el color original del botón "Añadir" al quitar el ratón.
    private void jLabelTextoAñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoAñadirMouseExited
        jPanelAñadir.setBackground(Color.WHITE);
        jLabelTextoAñadir.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabelTextoAñadirMouseExited

    // Carga las provincias correspondientes al seleccionar una comunidad.
    private void jComboBoxComunidadAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxComunidadAñadirActionPerformed
        contro.cargarProvincias(jComboBoxComunidadAñadir, jComboBoxProvinciaAñadir);
    }//GEN-LAST:event_jComboBoxComunidadAñadirActionPerformed
    
    // Aplica estilo FlatLaf a todos los JComboBox dentro del contenedor dado.
    private void aplicarFlatLafSoloCombosEnContenedir(Container container){
        for(Component c : container.getComponents()){
            if(c instanceof JComboBox){
                ((JComboBox<?>) c).setUI(new FlatComboBoxUI());
            }else if ( c instanceof Container){
                aplicarFlatLafSoloCombosEnContenedir((Container) c);
            }
        }
    }
    
    // Genera un ID único con prefijo "ID" seguido de 7 dígitos aleatorios.
    public static String generarIdUnico(){
        ConexionBBDD conexion = new ConexionBBDD();
        String nuevoId;
        do{
            int numero = (int)(Math.random() * 1_0000000);
            nuevoId = String.format("ID%07d", numero);
        }while(conexion.empresaExiste(nuevoId));
            conexion.cerrarConexion();
            return nuevoId;

    }
    // Cambia el color del texto de todos los campos y etiquetas a blanco.
    private void aplicarTextoBlnacoEnCampo(){
        jTextFieldIdEmpresaAñadir.setForeground(Color.WHITE);
        jTextFieldNombreEmpresaAñadir.setForeground(Color.WHITE);
        jTextFieldActividadAñadir.setForeground(Color.WHITE);
        jTextFieldSectorAñadir.setForeground(Color.WHITE);
        jTextFieldDireccionAñadir.setForeground(Color.WHITE);
        jTextFieldCodigoPostalAñadir.setForeground(Color.WHITE);
        jTextFieldPoblacionAñadir.setForeground(Color.WHITE);
        jTextFieldTelefonoAñadir.setForeground(Color.WHITE);
        jTextFieldFaxAñadir.setForeground(Color.WHITE);
        jTextFieldEmailAñadir.setForeground(Color.WHITE);
        jTextFieldEmailTestAñadir.setForeground(Color.WHITE);
        jTextFieldWebAñadir.setForeground(Color.WHITE);
        jComboBoxComunidadAñadir.setForeground(Color.WHITE);
        jComboBoxProvinciaAñadir.setForeground(Color.WHITE);
        
        jLabelTextoTituloAñadir.setForeground(Color.WHITE);
        jLabelTextoIdEmpresaAñadir.setForeground(Color.WHITE);
        jLabelTextoNombreEmpresaAñadir.setForeground(Color.WHITE);
        jLabelTextoActividadAñadir.setForeground(Color.WHITE);
        jLabelTextoSectorAñadir.setForeground(Color.WHITE);
        jLabelTextoEmailAñadir.setForeground(Color.WHITE);
        jLabelTextoFaxAñadir.setForeground(Color.WHITE);
        jLabelTextoTelefonoAñadir.setForeground(Color.WHITE);
        jLabelTextoDireccionAñadir.setForeground(Color.WHITE);
        jLabelTextoCodigoPostalAñadir.setForeground(Color.WHITE);
        jLabelTextoPoblacionAñadir.setForeground(Color.WHITE);
        jLabelTextoEmailTestAñadir.setForeground(Color.WHITE);
        jLabelTextoWebAñadir.setForeground(Color.WHITE);
        jLabelTextoComunidadAñadir.setForeground(Color.WHITE);
        jLabelTextoProvinciaAñadir.setForeground(Color.WHITE);                       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxComunidadAñadir;
    private javax.swing.JComboBox<String> jComboBoxProvinciaAñadir;
    private javax.swing.JLabel jLabelImagenAñadir;
    private javax.swing.JLabel jLabelTextoActividadAñadir;
    private javax.swing.JLabel jLabelTextoAñadir;
    private javax.swing.JLabel jLabelTextoCodigoPostalAñadir;
    private javax.swing.JLabel jLabelTextoComunidadAñadir;
    private javax.swing.JLabel jLabelTextoDireccionAñadir;
    private javax.swing.JLabel jLabelTextoEmailAñadir;
    private javax.swing.JLabel jLabelTextoEmailTestAñadir;
    private javax.swing.JLabel jLabelTextoFaxAñadir;
    private javax.swing.JLabel jLabelTextoIdAleatorioAñadir;
    private javax.swing.JLabel jLabelTextoIdEmpresaAñadir;
    private javax.swing.JLabel jLabelTextoNombreEmpresaAñadir;
    private javax.swing.JLabel jLabelTextoPoblacionAñadir;
    private javax.swing.JLabel jLabelTextoProvinciaAñadir;
    private javax.swing.JLabel jLabelTextoSectorAñadir;
    private javax.swing.JLabel jLabelTextoTelefonoAñadir;
    private javax.swing.JLabel jLabelTextoTituloAñadir;
    private javax.swing.JLabel jLabelTextoWebAñadir;
    private javax.swing.JPanel jPanelAñadir;
    private javax.swing.JPanel jPanelIdAleatorioAñadir;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextFieldActividadAñadir;
    private javax.swing.JTextField jTextFieldCodigoPostalAñadir;
    private javax.swing.JTextField jTextFieldDireccionAñadir;
    private javax.swing.JTextField jTextFieldEmailAñadir;
    private javax.swing.JTextField jTextFieldEmailTestAñadir;
    private javax.swing.JTextField jTextFieldFaxAñadir;
    private javax.swing.JTextField jTextFieldIdEmpresaAñadir;
    private javax.swing.JTextField jTextFieldNombreEmpresaAñadir;
    private javax.swing.JTextField jTextFieldPoblacionAñadir;
    private javax.swing.JTextField jTextFieldSectorAñadir;
    private javax.swing.JTextField jTextFieldTelefonoAñadir;
    private javax.swing.JTextField jTextFieldWebAñadir;
    // End of variables declaration//GEN-END:variables
}
