
package Inicio;


import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class PanelVerTodasLasEmpresas extends javax.swing.JPanel {

    private final Conexion.ConexionBBDD conexion = new Conexion.ConexionBBDD();
    private int paginaActual = 1;
    private final int registrosPorPagina = 100;
    
    public PanelVerTodasLasEmpresas() {
        initComponents();
        cargarPagina(paginaActual);
        aplicarTextoBlnacoEnCampo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTextoTituloVistaEmpresas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelTextoEacribaNombreEmpresaVistaEmpresas = new javax.swing.JLabel();
        jTextFieldEscribaNombreEmpresaVistaEmpresa = new javax.swing.JTextField();
        jPanelCargarDatosVerEmpresas = new PanelRound();
        jLabelTextoBuscarDatosVistaEmpresa = new javax.swing.JLabel();
        jPanelCancelarVistaEmpresas = new PanelRound();
        jLabelTextoCancelarVistaEmpresa = new javax.swing.JLabel();
        jLabelSiguienteVistaEmpresa = new javax.swing.JLabel();
        jLabelAnteriorVistaEmpresas = new javax.swing.JLabel();
        jTextAreaVerVistaEmpresa = new java.awt.TextArea();
        jLabelImagen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(41, 41, 41));
        setPreferredSize(new java.awt.Dimension(940, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextoTituloVistaEmpresas.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextoTituloVistaEmpresas.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelTextoTituloVistaEmpresas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoTituloVistaEmpresas.setText(" VISTA EMPRESA");
        add(jLabelTextoTituloVistaEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 210, 10));

        jLabelTextoEacribaNombreEmpresaVistaEmpresas.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextoEacribaNombreEmpresaVistaEmpresas.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoEacribaNombreEmpresaVistaEmpresas.setText("Escriba el nombre de la empresa");
        add(jLabelTextoEacribaNombreEmpresaVistaEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jTextFieldEscribaNombreEmpresaVistaEmpresa.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldEscribaNombreEmpresaVistaEmpresa.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldEscribaNombreEmpresaVistaEmpresa.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldEscribaNombreEmpresaVistaEmpresa.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldEscribaNombreEmpresaVistaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 240, 28));

        jLabelTextoBuscarDatosVistaEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextoBuscarDatosVistaEmpresa.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoBuscarDatosVistaEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoBuscarDatosVistaEmpresa.setText("Buscar");
        jLabelTextoBuscarDatosVistaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTextoBuscarDatosVistaEmpresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTextoBuscarDatosVistaEmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTextoBuscarDatosVistaEmpresaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCargarDatosVerEmpresasLayout = new javax.swing.GroupLayout(jPanelCargarDatosVerEmpresas);
        jPanelCargarDatosVerEmpresas.setLayout(jPanelCargarDatosVerEmpresasLayout);
        jPanelCargarDatosVerEmpresasLayout.setHorizontalGroup(
            jPanelCargarDatosVerEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCargarDatosVerEmpresasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTextoBuscarDatosVistaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCargarDatosVerEmpresasLayout.setVerticalGroup(
            jPanelCargarDatosVerEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCargarDatosVerEmpresasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTextoBuscarDatosVistaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelCargarDatosVerEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 110, 30));

        jLabelTextoCancelarVistaEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextoCancelarVistaEmpresa.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoCancelarVistaEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoCancelarVistaEmpresa.setText("Cancelar");
        jLabelTextoCancelarVistaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTextoCancelarVistaEmpresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTextoCancelarVistaEmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTextoCancelarVistaEmpresaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCancelarVistaEmpresasLayout = new javax.swing.GroupLayout(jPanelCancelarVistaEmpresas);
        jPanelCancelarVistaEmpresas.setLayout(jPanelCancelarVistaEmpresasLayout);
        jPanelCancelarVistaEmpresasLayout.setHorizontalGroup(
            jPanelCancelarVistaEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelarVistaEmpresasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTextoCancelarVistaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCancelarVistaEmpresasLayout.setVerticalGroup(
            jPanelCancelarVistaEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelarVistaEmpresasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTextoCancelarVistaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelCancelarVistaEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabelSiguienteVistaEmpresa.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelSiguienteVistaEmpresa.setText("Siguiente");
        jLabelSiguienteVistaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSiguienteVistaEmpresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSiguienteVistaEmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSiguienteVistaEmpresaMouseExited(evt);
            }
        });
        add(jLabelSiguienteVistaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, -1, -1));

        jLabelAnteriorVistaEmpresas.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelAnteriorVistaEmpresas.setText("Anterior");
        jLabelAnteriorVistaEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAnteriorVistaEmpresasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAnteriorVistaEmpresasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAnteriorVistaEmpresasMouseExited(evt);
            }
        });
        add(jLabelAnteriorVistaEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jTextAreaVerVistaEmpresa.setBackground(new java.awt.Color(41, 41, 41));
        jTextAreaVerVistaEmpresa.setEditable(false);
        jTextAreaVerVistaEmpresa.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextAreaVerVistaEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextAreaVerVistaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 920, 520));

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenModificar.png"))); // NOI18N
        add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTextoCancelarVistaEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoCancelarVistaEmpresaMouseClicked
        jTextFieldEscribaNombreEmpresaVistaEmpresa.setText("");
        jTextAreaVerVistaEmpresa.setText("");                   
        paginaActual = 1;                                       
        cargarPagina(paginaActual);  
    }//GEN-LAST:event_jLabelTextoCancelarVistaEmpresaMouseClicked

    private void jLabelTextoCancelarVistaEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoCancelarVistaEmpresaMouseEntered
        jPanelCancelarVistaEmpresas.setBackground(new Color(51, 51, 51));
        jLabelTextoCancelarVistaEmpresa.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelTextoCancelarVistaEmpresaMouseEntered

    private void jLabelTextoCancelarVistaEmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoCancelarVistaEmpresaMouseExited
        jPanelCancelarVistaEmpresas.setBackground(Color.WHITE);
        jLabelTextoCancelarVistaEmpresa.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabelTextoCancelarVistaEmpresaMouseExited

    private void jLabelTextoBuscarDatosVistaEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoBuscarDatosVistaEmpresaMouseClicked
        String texto = jTextFieldEscribaNombreEmpresaVistaEmpresa.getText().trim();

        if(texto.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor, escriba el nombre de la empresa a buscar.", 
                "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String textoNormalizado = normalizarTexto(texto);
        try{
            ArrayList<String[]> empresasFiltradas = conexion.buscarEmpresasPorNombreParcial(textoNormalizado);
            if(empresasFiltradas == null || empresasFiltradas.isEmpty()){
                jTextAreaVerVistaEmpresa.setText("No se encontraron resultados para: " + textoNormalizado);
            }else{
                mostrarEmpresasEnTextArea(empresasFiltradas);
            }
            jTextAreaVerVistaEmpresa.setCaretPosition(0);
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al buscar empresas:\n" + ex.getMessage(), 
                                          "Error de búsqueda", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelTextoBuscarDatosVistaEmpresaMouseClicked
    
    private String normalizarTexto(String input) {
        if (input == null) return "";
        return input.toUpperCase().trim();
    }

    private void jLabelTextoBuscarDatosVistaEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoBuscarDatosVistaEmpresaMouseEntered
        jPanelCargarDatosVerEmpresas.setBackground(new Color(51, 51, 51));
        jLabelTextoBuscarDatosVistaEmpresa.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelTextoBuscarDatosVistaEmpresaMouseEntered

    private void jLabelTextoBuscarDatosVistaEmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoBuscarDatosVistaEmpresaMouseExited
        jPanelCargarDatosVerEmpresas.setBackground(Color.WHITE);
        jLabelTextoBuscarDatosVistaEmpresa.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabelTextoBuscarDatosVistaEmpresaMouseExited

    private void jLabelSiguienteVistaEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSiguienteVistaEmpresaMouseClicked
        paginaActual++;
        cargarPagina(paginaActual);
    }//GEN-LAST:event_jLabelSiguienteVistaEmpresaMouseClicked

    private void jLabelAnteriorVistaEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAnteriorVistaEmpresasMouseClicked
        if(paginaActual > 1){
            paginaActual--;
            cargarPagina(paginaActual);
        }
    

    }//GEN-LAST:event_jLabelAnteriorVistaEmpresasMouseClicked

    private void jLabelSiguienteVistaEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSiguienteVistaEmpresaMouseEntered
        jLabelSiguienteVistaEmpresa.setBackground(Color.BLUE);
    }//GEN-LAST:event_jLabelSiguienteVistaEmpresaMouseEntered

    private void jLabelSiguienteVistaEmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSiguienteVistaEmpresaMouseExited
        jLabelSiguienteVistaEmpresa.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabelSiguienteVistaEmpresaMouseExited

    private void jLabelAnteriorVistaEmpresasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAnteriorVistaEmpresasMouseEntered
        jLabelAnteriorVistaEmpresas.setBackground(Color.BLUE);
    }//GEN-LAST:event_jLabelAnteriorVistaEmpresasMouseEntered

    private void jLabelAnteriorVistaEmpresasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAnteriorVistaEmpresasMouseExited
        jLabelAnteriorVistaEmpresas.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabelAnteriorVistaEmpresasMouseExited
    private void mostrarEmpresasEnTextArea(java.util.List<String[]> empresas) {
        StringBuilder sb = new StringBuilder();

        String formatoFila = "%-10s %-50s %-40s %-40s %-50s %-6s %-15s %-15s %-15s %-12s %-12s %-35s %-15s %-40s%n";

        sb.append(String.format(formatoFila,
                "ID", "EMPRESA", "ACTIVIDAD", "SECTOR", "DIRECCIÓN", "CP", "POBLACIÓN", "PROVINCIA",
                "COMUNIDAD", "TELÉFONO", "FAX", "EMAIL", "EMAIL_TEST", "WEB"));
        sb.append("=".repeat(365)).append("\n");
        
        
        for(String[] fila : empresas){
            if (fila.length < 14) continue;
            
            for(int i = 0; i < fila.length; i++){
                fila[i] = cleanText(fila[i]);
            }
            
            sb.append(String.format(formatoFila,
                truncate(fila[0], 10),
                truncate(fila[1], 50),
                truncate(fila[2], 40),
                truncate(fila[3], 40),
                truncate(fila[4], 50),
                truncate(fila[5], 6),
                truncate(fila[6], 15),
                truncate(fila[7], 15),
                truncate(fila[8], 15),
                truncate(fila[9], 12),
                truncate(fila[10], 12),
                truncate(fila[11], 35),
                truncate(fila[12], 15),
                truncate(fila[13], 40))
            );
            
            sb.append("-".repeat(365)).append("\n");
        }

        jTextAreaVerVistaEmpresa.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        jTextAreaVerVistaEmpresa.setText(sb.toString());
    }
    
    private String truncate(String text, int maxLength) {
        if(text == null) return "";
        return text.length() > maxLength ? text.substring(0, maxLength - 3) + "..." : text;
    }
    
    private void cargarPagina(int pagina) {
        int offset = (pagina - 1) * registrosPorPagina;       
        java.util.List<String[]> empresas = conexion.obtenerEmpresasPaginado(offset, registrosPorPagina);
        if(empresas.isEmpty() && pagina > 1){
            paginaActual--;
            return;
        }
        mostrarEmpresasEnTextArea(empresas);
        jTextAreaVerVistaEmpresa.setCaretPosition(0);
    }
    
    private String cleanText(String text) {
        return text == null ? "" : text.replaceAll("[\\t\\n\\r]+", " ").trim();
    }
       
    private void aplicarTextoBlnacoEnCampo(){
        jLabelTextoTituloVistaEmpresas.setForeground(Color.WHITE);
        jLabelTextoEacribaNombreEmpresaVistaEmpresas.setForeground(Color.WHITE);
        jTextFieldEscribaNombreEmpresaVistaEmpresa.setForeground(Color.WHITE);
        jLabelAnteriorVistaEmpresas.setForeground(Color.WHITE);
        jLabelSiguienteVistaEmpresa.setForeground(Color.WHITE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAnteriorVistaEmpresas;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelSiguienteVistaEmpresa;
    private javax.swing.JLabel jLabelTextoBuscarDatosVistaEmpresa;
    private javax.swing.JLabel jLabelTextoCancelarVistaEmpresa;
    private javax.swing.JLabel jLabelTextoEacribaNombreEmpresaVistaEmpresas;
    private javax.swing.JLabel jLabelTextoTituloVistaEmpresas;
    private javax.swing.JPanel jPanelCancelarVistaEmpresas;
    private javax.swing.JPanel jPanelCargarDatosVerEmpresas;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.TextArea jTextAreaVerVistaEmpresa;
    private javax.swing.JTextField jTextFieldEscribaNombreEmpresaVistaEmpresa;
    // End of variables declaration//GEN-END:variables
}
