/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Inicio;

/**
 *
 * @author eduar
 */
public class PanelVerTodasLasEmpresas extends javax.swing.JPanel {

    private final Conexion.ConexionBBDD conexion = new Conexion.ConexionBBDD();
    private int paginaActual = 1;
    private final int registrosPorPagina = 100;
    public PanelVerTodasLasEmpresas() {
        initComponents();
        cargarPagina(paginaActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVerVistaEmpresa = new javax.swing.JTextArea();
        jLabelTextoTituloModificar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelTextoEacribaNombreEmpresaModificar = new javax.swing.JLabel();
        jTextFieldEscribaNombreEmpresaVistaEmpresa = new javax.swing.JTextField();
        jPanelCargarDatosModificar = new PanelRound();
        jLabelTextoBuscarDatosVistaEmpresa = new javax.swing.JLabel();
        jPanelCargarDatosModificar1 = new PanelRound();
        jLabelTextoCancelarVistaEmpresa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(41, 41, 41));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaVerVistaEmpresa.setColumns(20);
        jTextAreaVerVistaEmpresa.setRows(5);
        jScrollPane1.setViewportView(jTextAreaVerVistaEmpresa);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 850, 500));

        jLabelTextoTituloModificar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextoTituloModificar.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelTextoTituloModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoTituloModificar.setText(" VISTA EMPRESA");
        add(jLabelTextoTituloModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 210, 10));

        jLabelTextoEacribaNombreEmpresaModificar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextoEacribaNombreEmpresaModificar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoEacribaNombreEmpresaModificar.setText("Escriba el nombre de la empresa");
        add(jLabelTextoEacribaNombreEmpresaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jTextFieldEscribaNombreEmpresaVistaEmpresa.setBackground(new java.awt.Color(90, 90, 90));
        jTextFieldEscribaNombreEmpresaVistaEmpresa.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextFieldEscribaNombreEmpresaVistaEmpresa.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8), null));
        jTextFieldEscribaNombreEmpresaVistaEmpresa.setMinimumSize(new java.awt.Dimension(64, 20));
        add(jTextFieldEscribaNombreEmpresaVistaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 240, 25));

        jLabelTextoBuscarDatosVistaEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextoBuscarDatosVistaEmpresa.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoBuscarDatosVistaEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoBuscarDatosVistaEmpresa.setText("Buscar");
        jLabelTextoBuscarDatosVistaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTextoBuscarDatosVistaEmpresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTextoBuscarDatosVistaEmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTextoBuscarDatosVistaEmpresaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCargarDatosModificarLayout = new javax.swing.GroupLayout(jPanelCargarDatosModificar);
        jPanelCargarDatosModificar.setLayout(jPanelCargarDatosModificarLayout);
        jPanelCargarDatosModificarLayout.setHorizontalGroup(
            jPanelCargarDatosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCargarDatosModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTextoBuscarDatosVistaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCargarDatosModificarLayout.setVerticalGroup(
            jPanelCargarDatosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCargarDatosModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTextoBuscarDatosVistaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelCargarDatosModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 110, 30));

        jLabelTextoCancelarVistaEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextoCancelarVistaEmpresa.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelTextoCancelarVistaEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoCancelarVistaEmpresa.setText("CANCELAR");
        jLabelTextoCancelarVistaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTextoCancelarVistaEmpresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTextoCancelarVistaEmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTextoCancelarVistaEmpresaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCargarDatosModificar1Layout = new javax.swing.GroupLayout(jPanelCargarDatosModificar1);
        jPanelCargarDatosModificar1.setLayout(jPanelCargarDatosModificar1Layout);
        jPanelCargarDatosModificar1Layout.setHorizontalGroup(
            jPanelCargarDatosModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCargarDatosModificar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTextoCancelarVistaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCargarDatosModificar1Layout.setVerticalGroup(
            jPanelCargarDatosModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCargarDatosModificar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTextoCancelarVistaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelCargarDatosModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel1.setText("Siguiente");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 610, -1, -1));

        jLabel2.setText("Anterior");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTextoCancelarVistaEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoCancelarVistaEmpresaMouseClicked
        jTextFieldEscribaNombreEmpresaVistaEmpresa.setText("");

    }//GEN-LAST:event_jLabelTextoCancelarVistaEmpresaMouseClicked

    private void jLabelTextoCancelarVistaEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoCancelarVistaEmpresaMouseEntered

    }//GEN-LAST:event_jLabelTextoCancelarVistaEmpresaMouseEntered

    private void jLabelTextoCancelarVistaEmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoCancelarVistaEmpresaMouseExited

    }//GEN-LAST:event_jLabelTextoCancelarVistaEmpresaMouseExited

    private void jLabelTextoBuscarDatosVistaEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoBuscarDatosVistaEmpresaMouseClicked
        String texto = jTextFieldEscribaNombreEmpresaVistaEmpresa.getText().trim();

        if (texto.isEmpty()) {

        } else {
            java.util.List<String[]> empresasFiltradas = conexion.buscarEmpresasPorNombreParcial(texto);
            mostrarEmpresasEnTextArea(empresasFiltradas);
        }
    }//GEN-LAST:event_jLabelTextoBuscarDatosVistaEmpresaMouseClicked

    private void jLabelTextoBuscarDatosVistaEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoBuscarDatosVistaEmpresaMouseEntered

    }//GEN-LAST:event_jLabelTextoBuscarDatosVistaEmpresaMouseEntered

    private void jLabelTextoBuscarDatosVistaEmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoBuscarDatosVistaEmpresaMouseExited

    }//GEN-LAST:event_jLabelTextoBuscarDatosVistaEmpresaMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        paginaActual++;
        cargarPagina(paginaActual);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(paginaActual > 1){
            paginaActual--;
            cargarPagina(paginaActual);
        }
    

    }//GEN-LAST:event_jLabel2MouseClicked
    private void mostrarEmpresasEnTextArea(java.util.List<String[]> empresas) {
        StringBuilder sb = new StringBuilder();

        // Cabecera
        sb.append("ID | EMPRESA | ACTIVIDAD | SECTOR | DIRECCIÓN | CP | POBLACIÓN | PROVINCIA | COMUNIDAD | TELÉFONO | FAX | EMAIL | EMAIL_TEST | WEB\n");
        sb.append("-----------------------------------------------------------------------------------------------------------------------------\n");

        // Datos
        for (String[] fila : empresas) {
            sb.append(String.join(" | ", fila)).append("\n");
        }

        jTextAreaVerVistaEmpresa.setText(sb.toString());
    }
    
    private void cargarPagina(int pagina) {
        int offset = (pagina - 1) * registrosPorPagina;
        java.util.List<String[]> empresas = conexion.obtenerEmpresasPaginado(offset, registrosPorPagina);

        if (empresas.isEmpty() && pagina > 1) {
            // No hay más datos, retrocede página
            paginaActual--;
            return;
        }

        mostrarEmpresasEnTextArea(empresas);
        }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTextoBuscarDatosVistaEmpresa;
    private javax.swing.JLabel jLabelTextoCancelarVistaEmpresa;
    private javax.swing.JLabel jLabelTextoEacribaNombreEmpresaModificar;
    private javax.swing.JLabel jLabelTextoTituloModificar;
    private javax.swing.JPanel jPanelCargarDatosModificar;
    private javax.swing.JPanel jPanelCargarDatosModificar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextAreaVerVistaEmpresa;
    private javax.swing.JTextField jTextFieldEscribaNombreEmpresaVistaEmpresa;
    // End of variables declaration//GEN-END:variables
}
