/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicio;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.Area;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class PantallaInicio extends javax.swing.JFrame {

    int xMouse, yMouse;
    private final HashMap<String, ArrayList<String>> comunidadesProvincias ;
    private final HashMap<String, String> equivalenciasComunidades = new HashMap<>();
    private final HashMap<String, String> equivalenciasProvincias = new HashMap<>();
    public PantallaInicio() {
        this.comunidadesProvincias = new HashMap<>();
        initComponents();
        inicializarEquivalencias();
        cargarComunidades();
        PanelInicio panelInicio = new PanelInicio();
        jPanelFondoPantallaInicio.setLayout(new BorderLayout());
        jPanelFondoPantallaInicio.removeAll();
        jPanelFondoPantallaInicio.add(panelInicio, BorderLayout.CENTER);
        jPanelFondoPantallaInicio.revalidate();
        jPanelFondoPantallaInicio.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipalPantallaInicio = new javax.swing.JPanel();
        jPanelParaSalirInicio = new javax.swing.JPanel();
        jLabelParaSalirInicio = new javax.swing.JLabel();
        jPanelMenuIzqInicio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelInicioMenu = new PanelRound();
        jLabelInicioMenu = new javax.swing.JLabel();
        jPanelAñadirMenu = new PanelRound();
        jLabelAñadirMenu = new javax.swing.JLabel();
        jPanelModificarMenu = new PanelRound();
        jLabelModificarMenu = new javax.swing.JLabel();
        jPanelEliminarMenu = new PanelRound();
        jLabelEliminarMenu = new javax.swing.JLabel();
        jPanelFiltrarEmpresasMenu = new PanelRound();
        jLabelFiltrarEmpresaMenu = new javax.swing.JLabel();
        jPanelVerEmpresasMenu = new PanelRound();
        jLabelVerEmpresasMenu = new javax.swing.JLabel();
        jPanelArrastrarPantalla = new javax.swing.JPanel();
        jPanelFondoPantallaInicio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanelPrincipalPantallaInicio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipalPantallaInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelParaSalirInicio.setBackground(new java.awt.Color(51, 51, 51));

        jLabelParaSalirInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelParaSalirInicio.setForeground(new java.awt.Color(0, 0, 0));
        jLabelParaSalirInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelParaSalirInicio.setText("X");
        jLabelParaSalirInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelParaSalirInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelParaSalirInicioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelParaSalirInicioLayout = new javax.swing.GroupLayout(jPanelParaSalirInicio);
        jPanelParaSalirInicio.setLayout(jPanelParaSalirInicioLayout);
        jPanelParaSalirInicioLayout.setHorizontalGroup(
            jPanelParaSalirInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParaSalirInicioLayout.createSequentialGroup()
                .addComponent(jLabelParaSalirInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 132, Short.MAX_VALUE))
        );
        jPanelParaSalirInicioLayout.setVerticalGroup(
            jPanelParaSalirInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParaSalirInicioLayout.createSequentialGroup()
                .addComponent(jLabelParaSalirInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPrincipalPantallaInicio.add(jPanelParaSalirInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jPanelMenuIzqInicio.setBackground(new java.awt.Color(51, 51, 51));
        jPanelMenuIzqInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenPantallaInicio.png"))); // NOI18N
        jPanelMenuIzqInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanelInicioMenu.setBackground(new java.awt.Color(51, 51, 51));

        jLabelInicioMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelInicioMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInicioMenu.setText("INICIO");
        jLabelInicioMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInicioMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelInicioMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelInicioMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicioMenuLayout = new javax.swing.GroupLayout(jPanelInicioMenu);
        jPanelInicioMenu.setLayout(jPanelInicioMenuLayout);
        jPanelInicioMenuLayout.setHorizontalGroup(
            jPanelInicioMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioMenuLayout.createSequentialGroup()
                .addComponent(jLabelInicioMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelInicioMenuLayout.setVerticalGroup(
            jPanelInicioMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInicioMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMenuIzqInicio.add(jPanelInicioMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 50));

        jPanelAñadirMenu.setBackground(new java.awt.Color(51, 51, 51));

        jLabelAñadirMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelAñadirMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAñadirMenu.setText("AÑADIR");
        jLabelAñadirMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAñadirMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAñadirMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAñadirMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelAñadirMenuLayout = new javax.swing.GroupLayout(jPanelAñadirMenu);
        jPanelAñadirMenu.setLayout(jPanelAñadirMenuLayout);
        jPanelAñadirMenuLayout.setHorizontalGroup(
            jPanelAñadirMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAñadirMenuLayout.createSequentialGroup()
                .addComponent(jLabelAñadirMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelAñadirMenuLayout.setVerticalGroup(
            jPanelAñadirMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAñadirMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMenuIzqInicio.add(jPanelAñadirMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jPanelModificarMenu.setBackground(new java.awt.Color(51, 51, 51));

        jLabelModificarMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelModificarMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModificarMenu.setText("MODIFICAR");
        jLabelModificarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelModificarMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelModificarMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelModificarMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelModificarMenuLayout = new javax.swing.GroupLayout(jPanelModificarMenu);
        jPanelModificarMenu.setLayout(jPanelModificarMenuLayout);
        jPanelModificarMenuLayout.setHorizontalGroup(
            jPanelModificarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificarMenuLayout.createSequentialGroup()
                .addComponent(jLabelModificarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelModificarMenuLayout.setVerticalGroup(
            jPanelModificarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelModificarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMenuIzqInicio.add(jPanelModificarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jPanelEliminarMenu.setBackground(new java.awt.Color(51, 51, 51));

        jLabelEliminarMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelEliminarMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEliminarMenu.setText("ELIMINAR");
        jLabelEliminarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEliminarMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEliminarMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEliminarMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelEliminarMenuLayout = new javax.swing.GroupLayout(jPanelEliminarMenu);
        jPanelEliminarMenu.setLayout(jPanelEliminarMenuLayout);
        jPanelEliminarMenuLayout.setHorizontalGroup(
            jPanelEliminarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarMenuLayout.createSequentialGroup()
                .addComponent(jLabelEliminarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelEliminarMenuLayout.setVerticalGroup(
            jPanelEliminarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEliminarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMenuIzqInicio.add(jPanelEliminarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jPanelFiltrarEmpresasMenu.setBackground(new java.awt.Color(51, 51, 51));

        jLabelFiltrarEmpresaMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelFiltrarEmpresaMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFiltrarEmpresaMenu.setText("FILTRAR EMPRESAS");
        jLabelFiltrarEmpresaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFiltrarEmpresaMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelFiltrarEmpresaMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelFiltrarEmpresaMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiltrarEmpresasMenuLayout = new javax.swing.GroupLayout(jPanelFiltrarEmpresasMenu);
        jPanelFiltrarEmpresasMenu.setLayout(jPanelFiltrarEmpresasMenuLayout);
        jPanelFiltrarEmpresasMenuLayout.setHorizontalGroup(
            jPanelFiltrarEmpresasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrarEmpresasMenuLayout.createSequentialGroup()
                .addComponent(jLabelFiltrarEmpresaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFiltrarEmpresasMenuLayout.setVerticalGroup(
            jPanelFiltrarEmpresasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFiltrarEmpresaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMenuIzqInicio.add(jPanelFiltrarEmpresasMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        jPanelVerEmpresasMenu.setBackground(new java.awt.Color(51, 51, 51));

        jLabelVerEmpresasMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelVerEmpresasMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVerEmpresasMenu.setText("VER EMPRESAS");
        jLabelVerEmpresasMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVerEmpresasMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelVerEmpresasMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelVerEmpresasMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelVerEmpresasMenuLayout = new javax.swing.GroupLayout(jPanelVerEmpresasMenu);
        jPanelVerEmpresasMenu.setLayout(jPanelVerEmpresasMenuLayout);
        jPanelVerEmpresasMenuLayout.setHorizontalGroup(
            jPanelVerEmpresasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerEmpresasMenuLayout.createSequentialGroup()
                .addComponent(jLabelVerEmpresasMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelVerEmpresasMenuLayout.setVerticalGroup(
            jPanelVerEmpresasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelVerEmpresasMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMenuIzqInicio.add(jPanelVerEmpresasMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        jPanelPrincipalPantallaInicio.add(jPanelMenuIzqInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 690));

        jPanelArrastrarPantalla.setBackground(new java.awt.Color(255, 255, 255));
        jPanelArrastrarPantalla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelArrastrarPantallaMouseDragged(evt);
            }
        });
        jPanelArrastrarPantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelArrastrarPantallaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelArrastrarPantallaLayout = new javax.swing.GroupLayout(jPanelArrastrarPantalla);
        jPanelArrastrarPantalla.setLayout(jPanelArrastrarPantallaLayout);
        jPanelArrastrarPantallaLayout.setHorizontalGroup(
            jPanelArrastrarPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanelArrastrarPantallaLayout.setVerticalGroup(
            jPanelArrastrarPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelPrincipalPantallaInicio.add(jPanelArrastrarPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1060, 30));

        javax.swing.GroupLayout jPanelFondoPantallaInicioLayout = new javax.swing.GroupLayout(jPanelFondoPantallaInicio);
        jPanelFondoPantallaInicio.setLayout(jPanelFondoPantallaInicioLayout);
        jPanelFondoPantallaInicioLayout.setHorizontalGroup(
            jPanelFondoPantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanelFondoPantallaInicioLayout.setVerticalGroup(
            jPanelFondoPantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanelPrincipalPantallaInicio.add(jPanelFondoPantallaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 940, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalPantallaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalPantallaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelParaSalirInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelParaSalirInicioMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelParaSalirInicioMouseClicked

    private void jPanelArrastrarPantallaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelArrastrarPantallaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();  
    }//GEN-LAST:event_jPanelArrastrarPantallaMousePressed

    private void jPanelArrastrarPantallaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelArrastrarPantallaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse ,y - yMouse);
                                    
    }//GEN-LAST:event_jPanelArrastrarPantallaMouseDragged

    private void jLabelInicioMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInicioMenuMouseEntered
        jPanelInicioMenu.setBackground(Color.WHITE);
        jLabelInicioMenu.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabelInicioMenuMouseEntered

    private void jLabelInicioMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInicioMenuMouseExited
        jPanelInicioMenu.setBackground(new Color(51, 51, 51));
        jLabelInicioMenu.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelInicioMenuMouseExited

    private void jLabelInicioMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInicioMenuMouseClicked
        // 1. Crea una instancia del nuevo panel
        PanelInicio panelInicio = new PanelInicio();

        // 2. Limpia el panel central (jPanel5) y agrega el nuevo panel
        jPanelFondoPantallaInicio.removeAll();
        jPanelFondoPantallaInicio.setLayout(new BorderLayout()); // asegúrate de tener layout correcto
        jPanelFondoPantallaInicio.add(panelInicio, BorderLayout.CENTER);

        // 3. Refresca visualmente
        jPanelFondoPantallaInicio.revalidate();
        jPanelFondoPantallaInicio.repaint();
    }//GEN-LAST:event_jLabelInicioMenuMouseClicked

    private void jLabelAñadirMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAñadirMenuMouseClicked
        // 1. Crea una instancia del nuevo panel
        PanelAñadir panelAñadir = new PanelAñadir();

        // 2. Limpia el panel central (jPanel5) y agrega el nuevo panel
        jPanelFondoPantallaInicio.removeAll();
        jPanelFondoPantallaInicio.setLayout(new BorderLayout()); // asegúrate de tener layout correcto
        jPanelFondoPantallaInicio.add(panelAñadir, BorderLayout.CENTER);

        // 3. Refresca visualmente
        jPanelFondoPantallaInicio.revalidate();
        jPanelFondoPantallaInicio.repaint();
    }//GEN-LAST:event_jLabelAñadirMenuMouseClicked

    private void jLabelAñadirMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAñadirMenuMouseEntered
        jPanelAñadirMenu.setBackground(Color.WHITE);
        jLabelAñadirMenu.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabelAñadirMenuMouseEntered

    private void jLabelAñadirMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAñadirMenuMouseExited
        jPanelAñadirMenu.setBackground(new Color(51, 51, 51));
        jLabelAñadirMenu.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelAñadirMenuMouseExited

    private void jLabelModificarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelModificarMenuMouseClicked
        // 1. Crea una instancia del nuevo panel
        PanelModificar panelModificar = new PanelModificar();

        // 2. Limpia el panel central (jPanel5) y agrega el nuevo panel
        jPanelFondoPantallaInicio.removeAll();
        jPanelFondoPantallaInicio.setLayout(new BorderLayout()); // asegúrate de tener layout correcto
        jPanelFondoPantallaInicio.add(panelModificar, BorderLayout.CENTER);

        // 3. Refresca visualmente
        jPanelFondoPantallaInicio.revalidate();
        jPanelFondoPantallaInicio.repaint();
    }//GEN-LAST:event_jLabelModificarMenuMouseClicked

    private void jLabelModificarMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelModificarMenuMouseEntered
        jPanelModificarMenu.setBackground(Color.WHITE);
        jLabelModificarMenu.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabelModificarMenuMouseEntered

    private void jLabelModificarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelModificarMenuMouseExited
        jPanelModificarMenu.setBackground(new Color(51, 51, 51));
        jLabelModificarMenu.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelModificarMenuMouseExited

    private void jLabelEliminarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEliminarMenuMouseClicked
        // 1. Crea una instancia del nuevo panel
        PanelEliminar panelEliminar = new PanelEliminar();

        // 2. Limpia el panel central (jPanel5) y agrega el nuevo panel
        jPanelFondoPantallaInicio.removeAll();
        jPanelFondoPantallaInicio.setLayout(new BorderLayout()); // asegúrate de tener layout correcto
        jPanelFondoPantallaInicio.add(panelEliminar, BorderLayout.CENTER);

        // 3. Refresca visualmente
        jPanelFondoPantallaInicio.revalidate();
        jPanelFondoPantallaInicio.repaint();
    }//GEN-LAST:event_jLabelEliminarMenuMouseClicked

    private void jLabelEliminarMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEliminarMenuMouseEntered
       jPanelEliminarMenu.setBackground(Color.WHITE);
       jLabelEliminarMenu.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabelEliminarMenuMouseEntered

    private void jLabelEliminarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEliminarMenuMouseExited
        jPanelEliminarMenu.setBackground(new Color(51, 51, 51));
        jLabelEliminarMenu.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelEliminarMenuMouseExited

    private void jLabelFiltrarEmpresaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFiltrarEmpresaMenuMouseClicked
        // 1. Crea una instancia del nuevo panel
        PanelFiltrar panelFiltrar = new PanelFiltrar();

        // 2. Limpia el panel central (jPanel5) y agrega el nuevo panel
        jPanelFondoPantallaInicio.removeAll();
        jPanelFondoPantallaInicio.setLayout(new BorderLayout()); // asegúrate de tener layout correcto
        jPanelFondoPantallaInicio.add(panelFiltrar, BorderLayout.CENTER);

        // 3. Refresca visualmente
        jPanelFondoPantallaInicio.revalidate();
        jPanelFondoPantallaInicio.repaint();
    }//GEN-LAST:event_jLabelFiltrarEmpresaMenuMouseClicked

    private void jLabelFiltrarEmpresaMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFiltrarEmpresaMenuMouseEntered
        jPanelFiltrarEmpresasMenu.setBackground(Color.WHITE);
        jLabelFiltrarEmpresaMenu.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabelFiltrarEmpresaMenuMouseEntered

    private void jLabelFiltrarEmpresaMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFiltrarEmpresaMenuMouseExited
        jPanelFiltrarEmpresasMenu.setBackground(new Color(51, 51, 51));
        jLabelFiltrarEmpresaMenu.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelFiltrarEmpresaMenuMouseExited

    private void jLabelVerEmpresasMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVerEmpresasMenuMouseClicked
        // 1. Crea una instancia del nuevo panel
        PanelVerTodasLasEmpresas panelVerEmpresas = new PanelVerTodasLasEmpresas();

        // 2. Limpia el panel central (jPanel5) y agrega el nuevo panel
        jPanelFondoPantallaInicio.removeAll();
        jPanelFondoPantallaInicio.setLayout(new BorderLayout()); // asegúrate de tener layout correcto
        jPanelFondoPantallaInicio.add(panelVerEmpresas, BorderLayout.CENTER);

        // 3. Refresca visualmente
        jPanelFondoPantallaInicio.revalidate();
        jPanelFondoPantallaInicio.repaint();
    }//GEN-LAST:event_jLabelVerEmpresasMenuMouseClicked

    private void jLabelVerEmpresasMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVerEmpresasMenuMouseEntered
        jPanelVerEmpresasMenu.setBackground(Color.WHITE);
        jLabelVerEmpresasMenu.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jLabelVerEmpresasMenuMouseEntered

    private void jLabelVerEmpresasMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVerEmpresasMenuMouseExited
        jPanelVerEmpresasMenu.setBackground(new Color(51, 51, 51));
        jLabelVerEmpresasMenu.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabelVerEmpresasMenuMouseExited
    
    public void cargarComunidadesEn(JComboBox<String> combo) {
        combo.removeAllItems();
        combo.addItem("");
        for (String comunidad : comunidadesProvincias.keySet()) {
            combo.addItem(comunidad);
        }
    }
    
    public void cargarProvincias(JComboBox<String> comboComunidad, JComboBox<String> comboProvincias) {
        comboProvincias.removeAllItems();
        String comunidad = (String) comboComunidad.getSelectedItem();

        if (comunidad != null && comunidadesProvincias.containsKey(comunidad)) {
            ArrayList<String> provincias = comunidadesProvincias.get(comunidad);
            for (String provincia : provincias) {
                comboProvincias.addItem(provincia);
            }
        }
    }
    
    private void cargarComunidades() {
        comunidadesProvincias.clear();

        ArrayList<String> andalucia = new ArrayList<>();
        andalucia.add("Almería");
        andalucia.add("Cádiz");
        andalucia.add("Córdoba");
        andalucia.add("Granada");
        andalucia.add("Huelva");
        andalucia.add("Jaén");
        andalucia.add("Málaga");
        andalucia.add("Sevilla");
        comunidadesProvincias.put("Andalucia", andalucia);

        ArrayList<String> aragon = new ArrayList<>();
        aragon.add("Huesca");
        aragon.add("Teruel");
        aragon.add("Zaragoza");
        comunidadesProvincias.put("Aragon", aragon);

        ArrayList<String> asturias = new ArrayList<>();
        asturias.add("Asturias");
        comunidadesProvincias.put("Asturias", asturias);

        ArrayList<String> baleares = new ArrayList<>();
        baleares.add("Islas Baleares");
        comunidadesProvincias.put("Baleares", baleares);

        ArrayList<String> canarias = new ArrayList<>();
        canarias.add("Las Palmas");
        canarias.add("Santa Cruz de Tenerife");
        comunidadesProvincias.put("Canarias", canarias);

        ArrayList<String> cantabria = new ArrayList<>();
        cantabria.add("Cantabria");
        comunidadesProvincias.put("Cantabria", cantabria);

        ArrayList<String> castillaLaMancha = new ArrayList<>();
        castillaLaMancha.add("Albacete");
        castillaLaMancha.add("Ciudad Real");
        castillaLaMancha.add("Cuenca");
        castillaLaMancha.add("Guadalajara");
        castillaLaMancha.add("Toledo");
        comunidadesProvincias.put("Castilla La Mancha", castillaLaMancha);

        ArrayList<String> castillaLeon = new ArrayList<>();
        castillaLeon.add("Ávila");
        castillaLeon.add("Burgos");
        castillaLeon.add("León");
        castillaLeon.add("Palencia");
        castillaLeon.add("Salamanca");
        castillaLeon.add("Segovia");
        castillaLeon.add("Soria");
        castillaLeon.add("Valladolid");
        castillaLeon.add("Zamora");
        comunidadesProvincias.put("Castilla Leon", castillaLeon);

        ArrayList<String> catalunya = new ArrayList<>();
        catalunya.add("Barcelona");
        catalunya.add("Girona");
        catalunya.add("Lleida");
        catalunya.add("Tarragona");
        comunidadesProvincias.put("Cataluña", catalunya);

        ArrayList<String> extremadura = new ArrayList<>();
        extremadura.add("Badajoz");
        extremadura.add("Cáceres");
        comunidadesProvincias.put("Extremadura", extremadura);

        ArrayList<String> galicia = new ArrayList<>();
        galicia.add("A Coruña");
        galicia.add("Lugo");
        galicia.add("Ourense");
        galicia.add("Pontevedra");
        comunidadesProvincias.put("Galicia", galicia);

        ArrayList<String> madrid = new ArrayList<>();
        madrid.add("Madrid");
        comunidadesProvincias.put("Madrid", madrid);

        ArrayList<String> murcia = new ArrayList<>();
        murcia.add("Murcia");
        comunidadesProvincias.put("Murcia", murcia);

        ArrayList<String> navarra = new ArrayList<>();
        navarra.add("Navarra");
        comunidadesProvincias.put("Navarra", navarra);

        ArrayList<String> paisVasco = new ArrayList<>();
        paisVasco.add("Álava");
        paisVasco.add("Guipúzcoa");
        paisVasco.add("Vizcaya");
        comunidadesProvincias.put("Euskadi", paisVasco);

        ArrayList<String> rioja = new ArrayList<>();
        rioja.add("La Rioja");
        comunidadesProvincias.put("La Rioja", rioja);

        ArrayList<String> valencia = new ArrayList<>();
        valencia.add("Alicante");
        valencia.add("Castellón");
        valencia.add("Valencia");
        comunidadesProvincias.put("Com. Valenciana", valencia);

        ArrayList<String> ceuta = new ArrayList<>();
        ceuta.add("Ceuta");
        comunidadesProvincias.put("Ceuta", ceuta);

        ArrayList<String> melilla = new ArrayList<>();
        melilla.add("Melilla");
        comunidadesProvincias.put("Melilla", melilla);       
    }
    
    private void inicializarEquivalencias() {
        inicializarEquivalenciasComunidades();
        inicializarEquivalenciasProvincias();
    }
    private void inicializarEquivalenciasComunidades(){
        
        equivalenciasComunidades.put("ANDALUCIA", "Andalucia");
        equivalenciasComunidades.put("ANDALUCÍA", "Andalucia");

        equivalenciasComunidades.put("ARAGON", "Aragon");
        equivalenciasComunidades.put("ARAGÓN", "Aragon");

        equivalenciasComunidades.put("ASTURIAS", "Asturias");

        equivalenciasComunidades.put("BALEARES", "Baleares");
        equivalenciasComunidades.put("ISLAS BALEARES", "Baleares");

        equivalenciasComunidades.put("CANARIAS", "Canarias");
        equivalenciasComunidades.put("ISLAS CANARIAS", "Canarias");

        equivalenciasComunidades.put("CANTABRIA", "Cantabria");

        equivalenciasComunidades.put("CASTILLA-LA MANCHA", "Castilla La Mancha");
        equivalenciasComunidades.put("CASTILLA LA MANCHA", "Castilla La Mancha");
        equivalenciasComunidades.put("C. LA MANCHA", "Castilla La Mancha");

        equivalenciasComunidades.put("CASTILLA LEON", "Castilla Leon");
        equivalenciasComunidades.put("CASTILLA LEÓN", "Castilla Leon");

        equivalenciasComunidades.put("CATALUÑA", "Cataluña");
        equivalenciasComunidades.put("CATALUNYA", "Cataluña");

        equivalenciasComunidades.put("CEUTA", "Ceuta");
        equivalenciasComunidades.put("MELILLA", "Melilla");

        equivalenciasComunidades.put("EXTREMADURA", "Extremadura");

        equivalenciasComunidades.put("GALICIA", "Galicia");

        equivalenciasComunidades.put("MADRID", "Madrid");
        equivalenciasComunidades.put("C. MADRID", "Madrid");
        equivalenciasComunidades.put("COM. MADRID", "Madrid");

        equivalenciasComunidades.put("MURCIA", "Murcia");

        equivalenciasComunidades.put("NAVARRA", "Navarra");

        equivalenciasComunidades.put("PAIS VASCO", "Euskadi");
        equivalenciasComunidades.put("PAÍS VASCO", "Euskadi");
        equivalenciasComunidades.put("EUSKADI", "Euskadi");

        equivalenciasComunidades.put("LA RIOJA", "La Rioja");
        equivalenciasComunidades.put("LA-RIOJA", "La Rioja");

        equivalenciasComunidades.put("C. VALENCIANA", "Com. Valenciana");
        equivalenciasComunidades.put("COM. VALENCIA", "Com. Valenciana");
        equivalenciasComunidades.put("VALENCIA", "Com. Valenciana");
        equivalenciasComunidades.put("COMUNIDAD VALENCIANA", "Com. Valenciana");
    }
    
    //Inicializa equivalencias entre variantes de nombres de provincias
    private void inicializarEquivalenciasProvincias() {
       
        // Comunidad Valenciana
        equivalenciasProvincias.put("VALENCIA", "Valencia");
        equivalenciasProvincias.put("CASTELLON", "Castellón");
        equivalenciasProvincias.put("CASTELLÓN", "Castellón");
        equivalenciasProvincias.put("ALICANTE", "Alicante");

        // Cataluña
        equivalenciasProvincias.put("BARCELONA", "Barcelona");
        equivalenciasProvincias.put("TARRAGONA", "Tarragona");
        equivalenciasProvincias.put("LLEIDA", "Lleida");
        equivalenciasProvincias.put("LERIDA", "Lleida");
        equivalenciasProvincias.put("GIRONA", "Girona");
        equivalenciasProvincias.put("GERONA", "Girona");

        // País Vasco
        equivalenciasProvincias.put("ALAVA", "Álava");
        equivalenciasProvincias.put("ÁLAVA", "Álava");
        equivalenciasProvincias.put("GUIPUZCOA", "Guipuzcoa");
        equivalenciasProvincias.put("GUIPÚZCOA", "Guipuzcoa");
        equivalenciasProvincias.put("VIZCAYA", "Vizcaya");
        equivalenciasProvincias.put("BIZKAIA", "Vizcaya");

        // Castilla y León
        equivalenciasProvincias.put("AVILA", "Ávila");
        equivalenciasProvincias.put("ÁVILA", "Ávila");
        equivalenciasProvincias.put("BURGOS", "Burgos");
        equivalenciasProvincias.put("LEON", "León");
        equivalenciasProvincias.put("PALENCIA", "Palencia");
        equivalenciasProvincias.put("SALAMANCA", "Salamanca");
        equivalenciasProvincias.put("SEGOVIA", "Segovia");
        equivalenciasProvincias.put("SORIA", "Soria");
        equivalenciasProvincias.put("VALLADOLID", "Valladolid");
        equivalenciasProvincias.put("ZAMORA", "Zamora");

        // Castilla-La Mancha
        equivalenciasProvincias.put("ALBACETE", "Albacete");
        equivalenciasProvincias.put("CIUDAD REAL", "Ciudad Real");
        equivalenciasProvincias.put("CUENCA", "Cuenca");
        equivalenciasProvincias.put("GUADALAJARA", "Guadalajara");
        equivalenciasProvincias.put("TOLEDO", "Toledo");

        // Andalucía
        equivalenciasProvincias.put("ALMERIA", "Almería");
        equivalenciasProvincias.put("ALMERÍA", "Almería");
        equivalenciasProvincias.put("CADIZ", "Cádiz");
        equivalenciasProvincias.put("CÁDIZ", "Cádiz");
        equivalenciasProvincias.put("CORDOBA", "Córdoba");
        equivalenciasProvincias.put("CÓRDOBA", "Córdoba");
        equivalenciasProvincias.put("GRANADA", "Granada");
        equivalenciasProvincias.put("HUELVA", "Huelva");
        equivalenciasProvincias.put("JAEN", "Jaén");
        equivalenciasProvincias.put("JAÉN", "Jaén");
        equivalenciasProvincias.put("MALAGA", "Málaga");
        equivalenciasProvincias.put("MÁLAGA", "Málaga");
        equivalenciasProvincias.put("SEVILLA", "Sevilla");

        // Aragón
        equivalenciasProvincias.put("HUESCA", "Huesca");
        equivalenciasProvincias.put("TERUEL", "Teruel");
        equivalenciasProvincias.put("ZARAGOZA", "Zaragoza");

        // Galicia
        equivalenciasProvincias.put("A CORUNA", "A Coruña");
        equivalenciasProvincias.put("A CORUÑA", "A Coruña");
        equivalenciasProvincias.put("LUGO", "Lugo");
        equivalenciasProvincias.put("OURENSE", "Ourense");
        equivalenciasProvincias.put("ORENSE", "Ourense");
        equivalenciasProvincias.put("PONTEVEDRA", "Pontevedra");

        // Extremadura
        equivalenciasProvincias.put("BADAJOZ", "Badajoz");
        equivalenciasProvincias.put("CACERES", "Cáceres");
        equivalenciasProvincias.put("CÁCERES", "Cáceres");

        // Madrid
        equivalenciasProvincias.put("MADRID", "Madrid");

        // Murcia
        equivalenciasProvincias.put("MURCIA", "Murcia");

        // Navarra
        equivalenciasProvincias.put("NAVARRA", "Navarra");

        // Asturias
        equivalenciasProvincias.put("ASTURIAS", "Asturias");

        // Cantabria
        equivalenciasProvincias.put("CANTABRIA", "Cantabria");

        // La Rioja
        equivalenciasProvincias.put("LA RIOJA", "La Rioja");

        // Baleares
        equivalenciasProvincias.put("BALEARES", "Islas Baleares");
        equivalenciasProvincias.put("ISLAS BALEARES", "Islas Baleares");

        // Canarias
        equivalenciasProvincias.put("LAS PALMAS", "Las Palmas");
        equivalenciasProvincias.put("SANTA CRUZ DE TENERIFE", "Santa Cruz de Tenerife");

        // Ceuta y Melilla
        equivalenciasProvincias.put("CEUTA", "Ceuta");
        equivalenciasProvincias.put("MELILLA", "Melilla");
    }
    
    private String normalizarNombreComunidad(String comunidad) {
        if (comunidad == null || comunidad.trim().isEmpty()){ 
            return "";
        }
        String comunidadClave = comunidad.trim().toUpperCase();
        return equivalenciasComunidades.getOrDefault(comunidadClave, comunidad);
    }
    
    //Normaliza el nombre de una provincia utilizando las equivalencias definidas
    private String mormalizarNombreProvincia(String provincia) {
        if (provincia == null || provincia.trim().isEmpty()){
            return "";
        }
        String provinciaClave = provincia.trim().toUpperCase();
        return equivalenciasProvincias.getOrDefault(provinciaClave, provincia);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAñadirMenu;
    private javax.swing.JLabel jLabelEliminarMenu;
    private javax.swing.JLabel jLabelFiltrarEmpresaMenu;
    private javax.swing.JLabel jLabelInicioMenu;
    private javax.swing.JLabel jLabelModificarMenu;
    private javax.swing.JLabel jLabelParaSalirInicio;
    private javax.swing.JLabel jLabelVerEmpresasMenu;
    private javax.swing.JPanel jPanelArrastrarPantalla;
    private javax.swing.JPanel jPanelAñadirMenu;
    private javax.swing.JPanel jPanelEliminarMenu;
    private javax.swing.JPanel jPanelFiltrarEmpresasMenu;
    private javax.swing.JPanel jPanelFondoPantallaInicio;
    private javax.swing.JPanel jPanelInicioMenu;
    private javax.swing.JPanel jPanelMenuIzqInicio;
    private javax.swing.JPanel jPanelModificarMenu;
    private javax.swing.JPanel jPanelParaSalirInicio;
    private javax.swing.JPanel jPanelPrincipalPantallaInicio;
    private javax.swing.JPanel jPanelVerEmpresasMenu;
    // End of variables declaration//GEN-END:variables
}

// Clase auxiliar agregada directamente al final de Login.java

class PanelRound extends JPanel {

    private int roundTopLeft = 50;
    private int roundTopRight = 50;
    private int roundBottomLeft = 50;
    private int roundBottomRight = 50;

    public PanelRound() {
        setOpaque(false);
    }

    public int getRoundTopLeft() {
        return roundTopLeft;
    }

    public void setRoundTopLeft(int roundTopLeft) {
        this.roundTopLeft = roundTopLeft;
        repaint();
    }

    public int getRoundTopRight() {
        return roundTopRight;
    }

    public void setRoundTopRight(int roundTopRight) {
        this.roundTopRight = roundTopRight;
        repaint();
    }

    public int getRoundBottomLeft() {
        return roundBottomLeft;
    }

    public void setRoundBottomLeft(int roundBottomLeft) {
        this.roundBottomLeft = roundBottomLeft;
        repaint();
    }

    public int getRoundBottomRight() {
        return roundBottomRight;
    }

    public void setRoundBottomRight(int roundBottomRight) {
        this.roundBottomRight = roundBottomRight;
        repaint();
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        Area area = new Area(createRoundTopLeft());
        if (roundTopRight > 0) {
            area.intersect(new Area(createRoundTopRight()));
        }
        if (roundBottomLeft > 0) {
            area.intersect(new Area(createRoundBottomLeft()));
        }
        if (roundBottomRight > 0) {
            area.intersect(new Area(createRoundBottomRight()));
        }
        g2.fill(area);
        g2.dispose();
        super.paintComponent(grphcs);
    }

    private Shape createRoundTopLeft() {
        int width = getWidth();
        int height = getHeight();
        int roundX = Math.min(width, roundTopLeft);
        int roundY = Math.min(height, roundTopLeft);
        Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, roundX, roundY));
        area.add(new Area(new Rectangle2D.Double(roundX / 2, 0, width - roundX / 2, height)));
        area.add(new Area(new Rectangle2D.Double(0, roundY / 2, width, height - roundY / 2)));
        return area;
    }

    private Shape createRoundTopRight() {
        int width = getWidth();
        int height = getHeight();
        int roundX = Math.min(width, roundTopRight);
        int roundY = Math.min(height, roundTopRight);
        Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, roundX, roundY));
        area.add(new Area(new Rectangle2D.Double(0, 0, width - roundX / 2, height)));
        area.add(new Area(new Rectangle2D.Double(0, roundY / 2, width, height - roundY / 2)));
        return area;
    }

    private Shape createRoundBottomLeft() {
        int width = getWidth();
        int height = getHeight();
        int roundX = Math.min(width, roundBottomLeft);
        int roundY = Math.min(height, roundBottomLeft);
        Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, roundX, roundY));
        area.add(new Area(new Rectangle2D.Double(roundX / 2, 0, width - roundX / 2, height)));
        area.add(new Area(new Rectangle2D.Double(0, 0, width, height - roundY / 2)));
        return area;
    }

    private Shape createRoundBottomRight() {
        int width = getWidth();
        int height = getHeight();
        int roundX = Math.min(width, roundBottomRight);
        int roundY = Math.min(height, roundBottomRight);
        Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, roundX, roundY));
        area.add(new Area(new Rectangle2D.Double(0, 0, width - roundX / 2, height)));
        area.add(new Area(new Rectangle2D.Double(0, 0, width, height - roundY / 2)));
        return area;
    }
}